### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by xuhcc** [appliedzkp/maci#127]
To use MACI in clr.fund, we need the following packages: `maci-contracts`, `maci-crypto` and `maci-domainobjs`. Currently I pack them manually and use tarballs, but it would be nice to have them on the NPM.

Some ideas:

- Make scoped packages (e.g. `@maci/contracts`).
- Add type definitions (I'll submit a PR for this soon).
- Having `maci-cli` packaged would be nice too (and there's a probability that we or someone else will need `maci-core`).

**Comment by weijiekoh** [comment]
I found the `lerna publish` command and used it. It seems that it worked!

https://www.npmjs.com/package/maci-crypto
https://www.npmjs.com/package/maci-domainobjs
https://www.npmjs.com/package/maci-core
https://www.npmjs.com/package/maci-contracts

**Comment by xuhcc** [comment]
Thanks, I successfully installed them in our project.

**Comment by xuhcc** [comment]
`maci-cli` works too. I guess this issue can be closed now.
