### ISSUE TITLE
[contracts] Update only single subtree node per insert

### ISSUE THREAD

**Issue by kilic** [appliedzkp/maci#131]
`insertLeaf` [here](https://github.com/appliedzkp/maci/blob/8c8c60c1e9fc9a9298aab45ed75854f1932c43e1/contracts/sol/IncrementalMerkleTree.sol#L133) updates all subtree nodes if path bit is zero. However single node update per insert would be enough for next insertions. 

Example code:

```
bytes32 acc = leaf;
uint256 path = leafIndex;
bool subtreeSet = false;
for (uint256 i = 0; i < DEPTH_LEFT; i++) {
  if (path & 1 == 1) {
    acc = keccak256(abi.encode(filledSubtrees[i], acc));
  } else {
    if (!subtreeSet) {
      filledSubtrees[i] = acc;
      subtreeSet = true;
    }
    acc = keccak256(abi.encode(acc, zeros[i]));
  }
  path >>= 1;
}
```

So that you can save more or less `depth/2 * 5000` gas per insert.

**Comment by weijiekoh** [comment]
Thank you! We are implementing a similar approach for the next version of MACI.

https://github.com/appliedzkp/maci/blob/v1/contracts/sol/trees/AccQueue.sol

Each enqueue operation updates a subtree. At some point in time, a coordinator will merge all the subtrees into a main tree.
