### ISSUE TITLE
[Feature Request] sign up and vote

### ISSUE THREAD

**Issue by barryWhiteHat** [appliedzkp/maci#170]
## Is your feature request related to a problem? Please describe.

At the moment when users sign up they have to wait until [`isAfterSignUpDeadline`](https://github.com/appliedzkp/maci/blob/master/contracts/sol/MACI.sol#L318) before they can submit their commands. 

This is bad UX where users have to take action, wait until the sign up period is over and then return in order to vote. 

The reason it is like this is to prevent users from being bribed as follows 

1. Sign up
2. Make bribe command
3. Command to set private key to 0x0. 

This way a user at sign up time can prove how they voted. To prevent this we prevent users from doing step 2 until after the sign up period. 

## Describe the solution you'd like

I would like messages that are published during the sign up period to be inserted into the command que to be processed after all other commands. So if a user does step 1 and 2 and 3 at sign up time. Step 1 is executed immediately but step 2 and 3 are deferred until the end of the voting period. Giving the bribee time to return later and change their vote. 

The change should be quite simple. 
Replace
```
        messageTree.insertLeaf(leaf);
```
With 

```
     if signupperiod:
        finalmessageTree.insertLeaf(leaf)
    else:
        messageTree.insertLeaf(leaf);
```

**Comment by weijiekoh** [comment]
Could we do it this way instead?

```
function signUp(PubKey _pubKey, Message _msg) public {
    StateLeaf leaf = hash(_pubKey, voiceCredits, ...);
    stateTree.insertLeaf(leaf);

    finalMessageTree.insertLeaf(hash(_msg));
}

function publishMessage(Message _msg) public {
    penultimateMessageTree.insertLeaf(hash(_msg));
}
```

And during message processing, process messages in `finalMessageTree` before processing those in `penultimateMessageTree`?

**Comment by weijiekoh** [comment]
@xuhcc @barryWhiteHat please let me know your thoughts on which approach we should take.

I think the latter approach is better UX as there won't be a signup period any more.

**Comment by xuhcc** [comment]
@weijiekoh In your approach a bribee is able to send overriding commands immediately after signup, right?

If that's the case, I agree that this is a preferred solution.

**Comment by barryWhiteHat** [comment]
> And during message processing, process messages in penultimateMessageTree before processing those in finalMessageTree?

This is basically what i was thinking. However there has to be a delay for `publishMessage` because if there is not I can sign up and imedietly insert a bribe message into the `penultimateMessageTree` however what we can do instead is process the messages in `penultimateMessageTree` as last in first out. This way i always have the chance to replace the message. 

Oh wait can we get rid of the two trees and just do last in first out ? Then you can have late signups that get bribed but we can just stop the sign up period and have a 1 day delay to allow users to put their anti bribe message. I need to think on this a bit more to make sure its okay.

**Comment by weijiekoh** [comment]
> can we get rid of the two trees and just do last in first out

I really like this idea! This will also make this an easier change than the two-tree solution.

**Comment by barryWhiteHat** [comment]
Cool. I thought about this and think it should work. Lets go for it :)

**Comment by xuhcc** [comment]
If messages are processed in reverse order of being published, the briber can ask user to publish a vote and a key-change message just before the end of the voting period. How can we protect from this attack?

**Comment by weijiekoh** [comment]
The user could publish this bribe-vote with an invalid nonce. As long as the attacker doesn't know at least one of the previous messages, they wouldn't know if the bribe-vote is valid or not.

**Comment by xuhcc** [comment]
But the briber can ask user to set the nonce of the bribe-vote to 1. So he will know that the nonce is valid.

**Comment by weijiekoh** [comment]
Uh oh - yes, then the briber could succeed!

But only one briber can succeed because only one message can be the last message to go into the message tree. If I'm a briber and I see one message enter the message tree right before the voting period ends, then I don't know if that message nullifies the bribe-vote.

This is much better than the previous model, where messages are processed in forward order, so any number of bribers could succeed. @barryWhiteHat - what do you think?

**Comment by barryWhiteHat** [comment]
I think htere is no way to order commands in a way that there is not a final command to be processed. 

I think this should be okay. We could randomly shuffle command batches but feel that is overkill.
