### ISSUE TITLE
PollFactory.deploy requires fails when "_treeDepths.messageTreeDepth" is greater than 3

### ISSUE THREAD

**Issue by exfinen** [appliedzkp/maci#314]
In maci/contracts/contracts/Poll.sol,

since the type of `treeArity` is `uint8`,
```
        uint8 treeArity = 5;   // line 63
```
in 
```
        require(   // line 73
            _maxValues.maxMessages <= treeArity ** _treeDepths.messageTreeDepth &&
            ...
```
`treeArity ** _treeDepths.messageTreeDepth` seems to overflow when `_treeDepths.messageTreeDepth` is greater than `3`, i.e. `5^3 = 125` but `5^4 = 625` which is larger than `256`, and that makes the require statement fail.

The type of `treeArity` should be a type that can store larger values without overflow.

I have created [a pull request](https://github.com/appliedzkp/maci/pull/313) to use uint16 instead of uint8. Please take a look.

**Comment by weijiekoh** [comment]
Thanks @exfinen! Made a small change to your PR and merged.
