### ISSUE TITLE
[circuits] a quadratic vote tally circuit which supports negative votes

### ISSUE THREAD

**Issue by weijiekoh** [appliedzkp/maci#68]
Suggestions on how to proceed with this task:

1. Clone the repository and try out the build and test steps: https://github.com/barryWhiteHat/maci/blob/master/README.md

2. Read the [spec](https://github.com/barryWhiteHat/maci/blob/master/SPEC.md) and focus on the `processMessage` contract functionn `updateStateTree` circuit, and quadratic vote tally circuit.

3. Modify the spec with the solution for negative votes

4. Modify the contract, circuits, and tests. The tests are:

    - `circuits/ts/__tests__/BatchUpdateStateTree.test.ts`
    - `circuits/ts/__tests__/UpdateStateTree.test.ts`
    - `circuits/ts/__tests__/QuadVoteTally.test.ts`
    - `contracts/ts/__tests__/Maci.test.ts`

5. Don't worry about `Maci.test.ts` at the start. It's perfectly fine to update it last.

6. Get familiar with the way that CircleCI performs a trusted setup whenever we modify a circuit, and take advantage of it to save time. You can download the circuit, proving keys, verification keys, and verifier contracts from CircleCI artifacts. See also: https://github.com/barryWhiteHat/maci/blob/master/.circleci/config.yml#L46

**Comment by ChihChengLiang** [comment]
Close this and renew with #109 for better motivation and design approach.
